config/routes.rb
Hotel::Application.routes.draw do
  
  

  devise_for :admins, :skip => [:sessions]
  as :admin do
    get 'admin_signin' => 'admins/devise/sessions#new', :as => :new_admin_session
    post 'admin_signin' => 'admins/devise/sessions#create', :as => :admin_session
    delete 'admin_signout' => 'admins/devise/sessions#destroy', :as => :destroy_admin_session
  end
  devise_for :users, :skip => [:sessions]
  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'home#index'
  get '/admins' => 'admins/home#index' 
  
  namespace :admins do
    resources :restaurants,:photos,:menus,:locations,:social_infos,:cities,:countries, :regions
    resources :getlocations do
      get "get_regions"
      get "get_cities"
    end
   
  end
 
  

  

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :regions
  has_many :locations
end

app/controllers/admins/cities_controller.rb
class Admins::CitiesController < ApplicationController
  layout "admin"
  def index
    @cities = City.all
    
  end
  def new
    @city = City.new
  end
  def create 
    
    @city = City.new(secure_params)
    
    if @city.save
      flash[:notice] = "Message sent from #{@city.name}."
      redirect_to  admins_cities_path
    else
      render :new
    end
  end
  private
  def secure_params
    params.require(:city).permit(:name)
  end
end

app/helpers/admins/cities_helper.rb
module Admins::CitiesHelper
end

app/views/admins/cities/index.html.erb
<ul class="nav nav-pills btn btn-default navbar-btn navbar-fixed-top">
  <li><%= link_to "Back", admins_path  %></li>
</ul>
<h1>All Cities</h1>

<table>

  <th>Name</th>


</table>
<%  @cities.each do |c|%>
  <table>
    <tr>

      <td><%= c.name %></td>
    </tr>
  </table> 
<%end%>

app/views/admins/cities/new.html.erb
<ul class="nav nav-pills btn btn-default navbar-btn navbar-fixed-top">
  <li><%= link_to "Back", admins_path  %></li>
</ul>
<%= form_for [:admins, @city] do |m| %>
  <div>
    <%= m.label :name %>
    <%= m.text_field :name, :required => true %>
  </div>
  <div>
  <%= m.collection_select(:country_id, Country.all,:id,:name,{include_blank:'Select Country'}) %>
</div>
  <div>
  <%= m.collection_select(:region_id, Region.all,:id,:name,{include_blank:'Select Region'}) %>
</div>
  <br />
  <%=  m.submit %>
<% end %>
  
<script type="text/javascript">
  $('#new_city').validate({});
</script>