config/routes.rb
Hotel::Application.routes.draw do
  
  

  devise_for :admins, :skip => [:sessions]
  as :admin do
    get 'admin_signin' => 'admins/devise/sessions#new', :as => :new_admin_session
    post 'admin_signin' => 'admins/devise/sessions#create', :as => :admin_session
    delete 'admin_signout' => 'admins/devise/sessions#destroy', :as => :destroy_admin_session
  end
  devise_for :users, :skip => [:sessions]
  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'home#index'
  get '/admins' => 'admins/home#index' 
  
  namespace :admins do
    resources :restaurants,:photos,:menus,:locations,:social_infos,:cities,:countries, :regions
    resources :getlocations do
      get "get_regions"
      get "get_cities"
    end
   
  end
 
  

  

end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
  layout "admin"
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:show,:index]
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/home/index.html.erb
<br />
<%= "Welcome" %>
<ul class="nav nav-pills btn btn-default navbar-btn navbar-fixed-top">
  <li><%= link_to "Add New Restaurant",new_admins_restaurant_path  %></li>
  <li><%=link_to  "Add New Menu", new_admins_menu_path %></li>
  <li><%= link_to "Add Social Info",  new_admins_social_info_path  %></li>
  <li><%= link_to "Add Location",  new_admins_location_path  %></li>
  <li><%= link_to "Add New City",  new_admins_city_path  %></li>
  <li><%= link_to "Add New Country",  new_admins_country_path  %></li>
  <li><%= link_to "Add New Region",   new_admins_region_path  %></li>
  <li class="pull-right">
    <% if admin_signed_in? %>
      <%= current_admin.email   %>
      <%=  link_to "sign out" , destroy_admin_session_path, :method=>:delete%>
    <% end %>
  </li>
  <br />
</ul>