config/routes.rb
Hotel::Application.routes.draw do
  
  

  devise_for :admins, :skip => [:sessions]
  as :admin do
    get 'admin_signin' => 'admins/devise/sessions#new', :as => :new_admin_session
    post 'admin_signin' => 'admins/devise/sessions#create', :as => :admin_session
    delete 'admin_signout' => 'admins/devise/sessions#destroy', :as => :destroy_admin_session
  end
  devise_for :users, :skip => [:sessions]
  as :user do
    get    'signin' => 'devise/sessions#new', :as => :new_user_session
    post   'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root 'home#index'
  get '/admins' => 'admins/home#index' 
  
  namespace :admins do
    resources :restaurants,:photos,:menus,:locations,:social_infos,:cities,:countries, :regions
    resources :getlocations do
      get "get_regions"
      get "get_cities"
    end
   
  end
 
  

  

end

app/models/location.rb
class Location < ActiveRecord::Base
  #acts_as_gmappable
  #      def gmaps4rails_address
  #          address
  #      end
  #       def gmaps4rails_infowindow
  #         "<h4>#{name}</h4>" << "<h4>#{address}</h4>"
  #     end
  belongs_to  :restaurant
  belongs_to :city
end

app/controllers/admins/locations_controller.rb
class Admins::LocationsController < ApplicationController
  layout 'admin'
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
   @locations = Location.all
   
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
#    puts "ssssssssssssssss",params.inspect
#   put
    @location = Location.new(secure_params)
    
    if @location.save
      flash[:notice] = "Message sent from #{@location.name}."
      redirect_to  admins_locations_path
    else
      render :new
    end
  end
 

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private
  def secure_params
    params.require(:location).permit(:id, :name, :address, :start_time,:close_time, :city_id)
  end
  end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admins/locations/_form.html.erb
<%#= form_for [:admins, @location] do |f| %>
<%# if @location.errors.any? %>
<%#*<div id="error_explanation">%>
<%#*<h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>%>

<%#*<ul>%>
<%# @location.errors.full_messages.each do |msg| %>
<%#*<li><%= msg %></li>%>
<%# end %>
<%#*</ul>%>
<%#*</div>%>
<%# end %>
<%#*<div class="fields">%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, :required => true %>
  </div>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :close_time %><br>
    <%= f.time_select :close_time %>
  </div>

   <div>
    <%= select_tag :country_id, options_from_collection_for_select(Country.all, 'id', 'name'), {:default => 'Select Country', :onchange => "get_regions()"} %>
  </div>
 <%=  f.submit %>
<% end %>
  <%#=  select_tag 'country', options_from_collection_for_select(@country, 'id', 'name') %>
<%#= f.select :country_id, options_from_collection_for_select(Country.all, 'id', 'name'), {:default => 'Select Country', :onchange => "get_regions()"}%>
    <%#= f.collection_select(:country_id, Country.all,:id,:name,{include_blank:'Select City'}) %>
    <%#= f.collection_select(:city_id, City.all,:id,:name,{include_blank:'Select City'}) %>
  
<%#*</div>%>

 

app/views/admins/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/admins/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Gmaps</th>
      <th>Start time</th>
      <th>Close time</th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= location.longitude %></td>
        <td><%= location.latitude %></td>
        <td><%= location.gmaps %></td>
        <td><%= location.start_time %></td>
        <td><%= location.close_time %></td>
        <td><%= link_to 'Show', admins_locations_path %></td>
        <td><%= link_to 'Edit', edit_admins_location_path(location) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/locations/new.html.erb
<h1>New location</h1>
<%= render 'form' %>

<%= link_to 'Back', admins_locations_path %>

app/views/admins/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Gmaps:</strong>
  <%= @location.gmaps %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @location.start_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @location.close_time %>
</p>

<%= link_to 'Edit', edit_admins_menu_path(@location) %> |
<%= link_to 'Back', admins_location_path %>